Error out if profile isn't found

diff --git a/install-profile b/install-profile
--- a/install-profile
+++ b/install-profile
@@ -14,13 +14,20 @@ DOTBOT_BIN="bin/dotbot"
 
 BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-
-pushd "${BASE_DIR}"
+pushd "${BASE_DIR}" &>> /dev/null
 git submodule update --init --recursive --remote
+
+profile="${META_DIR}/${PROFILES_DIR}/$1"
+
+if [[ ! -f ${profile} ]]; then
+    echo "FATAL: Could not find profile (${profile})."
+    popd &>> /dev/null
+    exit 1
+fi
 
 while IFS= read -r config; do
     CONFIGS+=" ${config}"
-done < "${META_DIR}/${PROFILES_DIR}/$1"
+done < "${profile}"
 
 shift
 
@@ -33,4 +40,4 @@ for config in ${CONFIGS} ${@}; do
     "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c <(echo -e "$configContent")
 done
 
-popd
+popd &>> /dev/null
